config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get "/pages/friends", to: "pages#friends"

  resources :groups, only: %i[new index show create] do
    resources :movies, only: [:index]

    resources :user_groups, only: %i[new create show] do
      resources :user_movies, only: %i[create show]
    end
  end

  get "/groups/:id/results", to: "groups#results",  as: "results"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :movie_genres
  has_many :movies, through: :movie_genres

  has_many :groups
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groups
  has_many :users, through: :user_groups
  belongs_to :user

  belongs_to :genre

  attribute :password_confirmation, type: String

  validates :password, confirmation: true, presence: true
  validates :name, presence: true, length: { maximum: 15 }
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :movie_genres
  has_many :genres, through: :movie_genres

  has_many :user_movies
  has_many :user_groups, through: :user_movies
end

app/models/movie_genre.rb
class MovieGenre < ApplicationRecord
  belongs_to :movie
  belongs_to :genre
end

app/models/streamer.rb
class Streamer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :user_groups
  has_many :groups, through: :user_groups

  validates :name, presence: true, uniqueness: true
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  attr_accessor :password
  belongs_to :user
  belongs_to :group

  has_many :user_movies
  has_many :movies, through: :user_movies

  validates :user, :group, presence: true
  validates :user, uniqueness: { scope: :group }

  attribute :password, type: String
  validate :valid_password, on: :create

  

  private

  def valid_password
    return true if password == group.password

    errors.add(:password, "is invalid")
  end
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
  belongs_to :user_group
  belongs_to :movie
end

app/models/user_streamer.rb
class UserStreamer < ApplicationRecord
  belongs_to :user
  belongs_to :streamer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/genre_movies_controller.rb
class GenreMoviesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @genre = Genre.find(@group.genre_id)
    @movies = @genre.movies
    raise
    @user_group = @group.user_groups.where(user_id: current_user.id).first
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
    @genres = Genre.all
  end

  def show
    @group = Group.find(params[:id])
    @user_group = UserGroup.find_by(group: @group, user: current_user)
    if !@user_group.nil?
    @empty_movies = @user_group.movies.empty?
    end


    @group.user_groups.where(voted: false).empty? ? @non_votants = [] : @non_votants = @group.user_groups.where(voted: false)

  end

  def index
    @groups = Group.all
  end

  def edit
    @group = Group.find(params[:id])
  end

  def destroy
    @group = Group.delete(params[:id])
  end

  def create
    @group = Group.new(group_params)
    @group.genre_id = group_params[:genre_id]
    @group.user = current_user
    # auto-join group creator
    if @group.save
      UserGroup.create(user: current_user, group: @group, password: group_params[:password])
      redirect_to group_path(@group)
    else
      render :new
    end
  end

  def results
    @group = Group.find(params[:id])
    @results = movie_counter(@group)
    @results = @results.sort {|a,b| b[1] <=> a[1]}
  end

  private

  def group_params
    params.require(:group).permit(:name, :genre_id, :password, :password_confirmation)
  end

  def movie_counter(group)
    results = {}
    group.user_groups.each do |user_group|
      user_group.movies.each do |movie|
        if results[movie].nil?
          results[movie] = 1
        else
          results[movie] += 1
        end
      end
    end
    results.map { |movie, value| [movie, value.to_f / group.users.length] }
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @genre = Genre.find(@group.genre_id)
    @movies = @genre.movies
    @user_group = UserGroup.where(group: @group, user: current_user).first


    #@user_group = @group.user_groups.where(user_id: current_user.id).first

  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end

  def friends
    @groups = Group.all
  end
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @user_group = UserGroup.new(user_group_params)
    @user_group.user = current_user
    @user_group.group = @group
    if @user_group.save
      redirect_to group_path(@group) # fix path to genre_movies
    else
      render :new
    end
  end

  def new
    @group = Group.find(params[:group_id])
    @user_group = UserGroup.new
    if @group.users.include?(current_user)
      #redirect_to group_user_genres_path(@group)
      redirect_to @group
    else
      render :new
    end
  end

  def show
    @user_movie = UserMovie.find(params[:user_movie])
    # @user_group = UserGroup.find(params[:id])
  end

  private

  def user_group_params
    params.require(:user_group).permit(:password)
  end
end

app/controllers/user_movies_controller.rb
class UserMoviesController < ApplicationController
  def create
    @group = Group.find(params[:group_id])
    @user_group = UserGroup.find(params[:user_group_id])
      #get the movies that we select from the form (with the ID) and then store it in the movies array
    @movies = []
    params["movies"].keys.each do |movie_id|
      movie = Movie.find(movie_id)
      @movies << movie
    end
    
    #create a record on the User Movies table based on each movie
    @movies.each do |movie|
      @user_movie = UserMovie.new(user_group: @user_group, movie: movie)
      @user_movie.save
    end

    #change the status of voted to true
    @group.user_groups.where(user: current_user).first.update(voted: true)
    
    #redirect
    redirect_to @group


    # if @user_movie.save
    #   redirect_to @group
    # else
    #   render :new
    # end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/groups/index.html.erb
<!-- DISPLAY GROUPS TO JOIN ONE PAGE -->
<!-- CSS file -> components/_index.css -->


  <!--<p>Search for groups</p>-->
  <div class="container">

  <div class="banner-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.livingmagazine.net/wp-content/uploads/Home-A-Night-In-at-the-Movies-1p_web1.jpg)">
    <h1>Join your group!</h1>
  </div>
  <% if @groups.empty? %>
    <p class="">No groups</p>
  <% else %>
    <% @groups.each do |group| %>
      <%= link_to group_path(group), class: "group-link" do %>
        <br>
        <div class="button-1">
        <%= group.name %>
        <br>
        <i class="fas fa-users"></i> <span><%= group.genre.name %>
        </span>

        </div>
      <% end %>
    <% end %>
  <% end %>
  <br>
  <br>
  <br>
</div>
  <%= link_to 'Back', pages_friends_path, class: "back-button-1" %>

app/views/groups/new.html.erb
<!-- CREATE GROUP PAGE -->
<!-- CSS file -> components/_sign_up.scss -->
<div class="container text-center">
  <i class="fas fa-users fa-8x"></i>

  <div class="create-group-page">
    <%= simple_form_for @group do |f| %>
      <%= f.error_notification %>
      <%= f.input :name %>
      <%= f.input :genre_id, collection: @genres %>
      <%= f.input :password, required: true %>
      <%= f.input :password_confirmation, required: true %>
      <br>
      <%= f.submit "Create a group", class: "button-1"  %>
    <% end %>
    <br>
    <br>
    <br>
</div>
</div>
  <%= link_to 'Back', pages_friends_path, class: "back-button-1" %>

app/views/groups/results.html.erb
<div class="container">
  <h1>Matching results: </h1>
  <br>
  <% @results.each do |result| %>
  <!-- start the card-->
  <div class="card-product">
    <img src="<%= result.first.image %>" />
    <div class="card-product-infos">
    <div style="margin-bottom: 30px;">
      <h2><%= result[0].title %></h2>
      <%= link_to "https://www.imdb.com/title/#{result.first.imdbid}" do %>
        <%= image_tag "imdb-logo.png", style: "height: auto; width: 50px;" %>
      <% end %>
    </div>
      <p><%= (result[0].length / 60).to_i %>m</p>
  </div>

    <div class="card-product-extra">
      <%= link_to "https://www.netflix.com/watch/#{result.first.nfid}" do %>
        <%= image_tag "netflix-logo.png", style: "height: auto; width: 90px; margin-top: 28px" %>
      <% end %>

      <div class="card-product-extra-percentage"><p><%= (result[1] * 100).round %>%</p></div>
    </div>
  <!-- finish the card-->
  </div>
  <% end %>
  <div class="back-to-groups-button" style="margin-top: 60px;">
    <%= link_to "Back to Groups", groups_path(@group), class: "back-button-1" %>
  </div>
</div>

app/views/groups/show.html.erb
<!-- DISPLAY LIST/INDEX/DETAILS OF USERS/GROUPS -->
<!-- CSS file -> components/_group-show.scss -->

<% content_for :meta_title, "#{@group.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @group.name %>
<%# content_for :meta_image, cl_image_path(@group.photo.path) %>
<div class="container text-center">
<br>
    <div class="black-card">
      <h2 style="font-size: 26px;"><%= @group.name %></h2>
      <p><%= @group.genre.name %></p>
      <p>Created by: <%= @group.user.name %></p>
    </div>

 <div class="black-card">
    <i class="fas fa-users fa-2x" style="margin-bottom: 10px;"></i>
    <% @group.users.each do |user| %>
        <p><%= user.name %></p>
    <% end %>
  </div>

  <% if current_user.groups.include?(@group) %>
  <% else %>
  <div class="black-card container">
    <%= simple_form_for [@group, UserGroup.new] do |f| %>
      <%= f.error_notification %>
      <%= f.input :password, required: true %>
      <%= f.submit 'Join',  class: "button-1" %>
    <% end %>
   </div>
  <% end %>



  <% if !@non_votants.empty? %>
    <div class="black-card" style="margin-top: 30px;">
    <p>Waiting for...</p>
    <% @non_votants.each do |non_votant| %>
      <p><%= non_votant.user.name %></p>
      <% end %>
    </div>
  <% end %>
  <% if @empty_movies %>
    <br>
    <%= link_to 'Start voting', group_movies_path(@group),  class: "button-1" %>

  <% else %>
    <% if !@user_group.nil? %>
    <div class="black-card">
    <h2>You voted for...</h2>
      <% @user_group.movies.each do |movie| %>
        <p><%= movie.title %></p>
      <% end %>
      </div>
    <% end %>
  <% end %>

  <br>
  <% if @non_votants.empty? && current_user.groups.include?(Group.find(params[:id]))%>
  <%= link_to "Results", results_path(@group), class: "button-1", id: "results" %>
  <% else %>
  <% end %>

</div>



  <!-- <div>
    <%#= link_to 'Back', groups_path, class: "button", id: "back"%>
  </div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieFinder - finding the movie you want in lesser time</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <title><%= meta_title %></title>
<meta name="description" content="<%= meta_description %>">

<!-- Facebook Open Graph data -->
<meta property="og:title" content="<%= meta_title %>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="<%= request.original_url %>" />
<meta property="og:image" content="<%= meta_image %>" />
<meta property="og:image:width" content="1200"/>
<meta property="og:image:height" content="630"/>
<meta property="og:description" content="<%= meta_description %>" />
<meta property="og:site_name" content="<%= meta_title %>" />

<!-- Twitter Card data -->
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:title" content="<%= meta_title %>">
<meta name="twitter:description" content="<%= meta_description %>">
<meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
<meta name="twitter:image:src" content="<%= meta_image %>">

  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container text-center">
<div class= "group-info-container container">
<div class="group-card-4">
  <h1>Movies</h1>
  <p>Pick your favourites below!</p>
  <br>
  <%= simple_form_for [@group, @user_group, UserMovie.new] do |f| %>
      <%= f.error_notification %>
     <%  @movies.each do |movie| %>
      <p></p>
      <div class="card-product text-center d-flex">
            <img src="<%= movie.image %>" style="height: 130px;"/>
            <div class="selection">
            <input class="movie_choice_input" type="checkbox" id="<%= movie.title %>" name="movies[<%= movie.id %>]">
            <label for="<%= movie.title %>" style="padding: 10px 20px"><%= movie.title %></label>
            </div>
            <%= link_to "https://www.imdb.com/title/#{movie.imdbid}" do %>
              <%= image_tag "imdb-logo.png", style: "height: auto; width: 50px;" %>
            <% end %>
      </div>
     <% end %>
      <%#= f.association :movie, include_blank: false,label: false %>
      <br>
      <br>
      <br>
      <%= f.submit "Submit my vote", class: "button-1" %>
  <% end %>
    </div>
</div>
</div>

app/views/pages/friends.html.erb
<!-- JOIN GROUP OR CREATE GROUP PAGE -->
<!-- CSS file -> components/_friends.scss -->

<body>
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://espalhafactos.com/wp-content/uploads/2020/03/Cinema-iStock.jpg);">
    <div class="containerfriends text-center container" >
      <h1>Let's go!</h1>
      <br>
      <br>

        <% if @groups.empty? %>
          <!--<button type="button" class="btn btn-lg btn-primary" disabled>Join group</button>-->
        <% else %>
          <%= link_to "Join group", groups_path, class: "button-1"%>
        <% end %>
        <%= link_to "Create group", new_group_path, class: "button-1", style: "margin-top: 15px;" %>

    </div>
  </div>
</body>

app/views/pages/home.html.erb
<!-- WELCOME TO MOVIE_FINDER/(GET STARTED) PAGE(HOMEPAGE) -->
<!-- CSS file -> components/_home.scss -->


<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://as1.ftcdn.net/v2/jpg/00/59/43/46/1000_F_59434607_heFSOwfHJjrrhfxKC0xWu7Ro06PXtFhQ.jpg);">
  <div class="container text-center">
    <h1 style="margin-bottom: 7px;">Welcome to <br>  <strong>MOVIE FINDER</strong></h1>
    <p></p>
    <br>
    <br>
    <%= link_to "Get started", "/pages/friends", class:"button-1" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
  <% end %>

<%= link_to pages_friends_path do %>
      <!--<i class="fas fa-film logo" ></i>-->
      <!--<p>MOVIE FINDER</p>-->
      <!-- <i class="fas fa-bars menu"></i>-->

      <div class="logo">
      <%= image_tag "logo1.png" %>

  </div>
<% end %>
  <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler"></span>
  </button> -->


  <!-- <div class="collapse navbar-collapse " id="navbarSupportedContent"> -->
    <div>
      <ul class="navbar-nav mr-auto" >
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <%= image_tag "menu.png", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, class: "avatar-dropdown" %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <div id="username">
                <p>User: <%= current_user.name if !current_user.nil? %> </p>
              </div>
              <%= link_to "Home", pages_friends_path, class: "dropdown-item" %>
              <!-- <%= link_to "Movies", "#", class: "dropdown-item" %>
              <%= link_to "Series", "#", class: "dropdown-item" %>
              <%= link_to "TV Shows", "#", class: "dropdown-item" %>
              <%= link_to "Genres", "#", class: "dropdown-item" %>
              <%= link_to "Settings", "#", class: "dropdown-item" %>
              <%= link_to "Privacy Policy", "#", class: "dropdown-item" %>
              <%= link_to "Help Center", "#", class: "dropdown-item" %> -->
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>

        <li class="nav-item my-nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link my-nav-link" %>
          </li>

        <% end %>

      </ul>
    </div>
</div>

app/views/user_groups/new.html.erb
<!-- ENTER PASSWORD TO JOIN GROUP PAGE -->
<%= simple_form_for [@group, @user_group] do |f| %>
  <%= f.input :password, required: true %>
  <%= f.submit "Join group" %>
<% end %>